name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to test (optional, defaults to production)'
        required: false
        default: 'https://www.monconbuild.com'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Run Lighthouse Tests
    
    strategy:
      matrix:
        page:
          - url: 'https://www.monconbuild.com/'
            name: 'Home'
          - url: 'https://www.monconbuild.com/services'
            name: 'Services'
          - url: 'https://www.monconbuild.com/about'
            name: 'About'
          - url: 'https://www.monconbuild.com/portfolio'
            name: 'Portfolio'
          - url: 'https://www.monconbuild.com/contact'
            name: 'Contact'
          - url: 'https://www.monconbuild.com/services/finish-carpentry'
            name: 'Finish Carpentry'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run Lighthouse Test via API
        id: lighthouse
        run: |
          echo "Testing ${{ matrix.page.name }}: ${{ matrix.page.url }}"
          
          RESPONSE=$(curl -s -X POST https://lighthouse-metrics.com/v1/lighthouse/checks \
            -H "Content-Type: application/json" \
            -d '{
              "url": "${{ matrix.page.url }}",
              "regions": ["us-west1"]
            }')
          
          echo "Response: $RESPONSE"
          echo "response=$RESPONSE" >> $GITHUB_OUTPUT

      - name: Parse Lighthouse Results
        run: |
          echo "Lighthouse test completed for ${{ matrix.page.name }}"
          echo "Check results at: https://lighthouse-metrics.com"

      - name: Comment PR with Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const pageName = '${{ matrix.page.name }}';
            const url = '${{ matrix.page.url }}';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚦 Lighthouse Results for ${pageName}\n\n` +
                    `**URL:** ${url}\n\n` +
                    `Lighthouse test has been triggered. View detailed results at [lighthouse-metrics.com](https://lighthouse-metrics.com)\n\n` +
                    `_Automated by Lighthouse CI_`
            });
